### ISSUE TITLE
Failure to Authenticate in Services 2.1.4

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#114]
Believed to be related to the library updates that occurred in the 2.1.4 release.

Information from Google,
https://developer.android.com/about/versions/pie/android-9.0-migration#tya

This is the stacktrace,
java.lang.SecurityException: Permission Denial: startForeground from pid=10646, uid=10189 requires android.permission.FOREGROUND_SERVICE
at android.os.Parcel.createException(Parcel.java:1953)
at android.os.Parcel.readException(Parcel.java:1921)
at android.os.Parcel.readException(Parcel.java:1871)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:5176)
at android.app.Service.startForeground(Service.java:701)
at org.opendatakit.services.sync.service.GlobalSyncNotificationManagerImpl.createNotification(GlobalSyncNotificationManagerImpl.java:150)
at org.opendatakit.services.sync.service.GlobalSyncNotificationManagerImpl.update(GlobalSyncNotificationManagerImpl.java:115)
at org.opendatakit.services.sync.service.GlobalSyncNotificationManagerImpl.startingSync(GlobalSyncNotificationManagerImpl.java:69)
at org.opendatakit.services.sync.service.AppSynchronizer$SyncTask.run(AppSynchronizer.java:187)
at java.lang.Thread.run(Thread.java:784)
Caused by: android.os.RemoteException: Remote stack trace:
at com.android.server.am.ActivityManagerService.enforcePermission(ActivityManagerService.java:10319)
at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1284)
at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:962)
at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:22128)
at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:10501)

E/SyncProgressTracker: 2019-09-13 00:59:00.791 FINAL SYNC Notification -default TEXT:Internal Error.

**Comment by wbrunette** [comment]
Pull request submitted as a solution: https://github.com/opendatakit/services/pull/143
