### ISSUE TITLE
Fix Null Pointer on Services launch

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#227]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{org.opendatakit.services/org.opendatakit.services.preferences.activities.AppPropertiesActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.opendatakit.properties.PropertiesSingleton.containsKey(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
       at android.app.ActivityThread.-wrap18()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.opendatakit.properties.PropertiesSingleton.containsKey(java.lang.String)' on a null object reference
       at org.opendatakit.services.preferences.fragments.AbsAdminConfigurableSettingsFragment.initializeCheckBoxPreference(AbsAdminConfigurableSettingsFragment.java:42)
       at org.opendatakit.services.preferences.fragments.AbsAdminConfigurableSettingsFragment.initializeCheckBoxPreference(AbsAdminConfigurableSettingsFragment.java:55)
       at org.opendatakit.services.preferences.fragments.AbsAdminConfigurableSettingsFragment.onCreate(AbsAdminConfigurableSettingsFragment.java:31)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2938)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3124)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3057)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
       at org.opendatakit.services.preferences.activities.AppPropertiesActivity.onCreate(AppPropertiesActivity.java:80)
       at android.app.Activity.performCreate(Activity.java:7009)
       at android.app.Activity.performCreate(Activity.java:7000)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4699)
       at android.app.ActivityThread.-wrap18()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1595)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by VarunT11** [comment]
@wbrunette Can I look into this?

**Comment by wbrunette** [comment]
@VarunT11 I have assigned this to you. Please make sure to finish your other open issues as well or asked to be removed.

**Comment by VarunT11** [comment]
@wbrunette Could you please guide me as to how to reproduce this issue as I tried a lot launching **Services** using various methods but did not find any Null Pointer Error.

**Comment by linl33** [comment]
@VarunT11
The steps are
1. Open Services
2. Open Settings
3. Enable user restrictions / enter admin mode
4. Click 'Manage ability to change server settings'
5. Rotate screen
6. Crash

**Comment by VarunT11** [comment]
@linl33 Thank You for guiding me! I have made a PR fixing this bug at https://github.com/odk-x/services/pull/203.
