### ISSUE TITLE
Fix Null Pointer OnItemSelected in MainActivity 

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#228]
Here is the error:

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setFocusableInTouchMode(boolean)' on a null object reference
       at org.opendatakit.services.MainActivity.onOptionsItemSelected(MainActivity.java:164)
       at android.app.Activity.onMenuItemSelected(Activity.java:4137)
       at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:340)
       at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:228)
       at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
       at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1176)
       at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
       at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
       at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
       at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
       at android.widget.AdapterView.performItemClick(AdapterView.java:330)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
       at android.widget.AbsListView.onTouchUp(AbsListView.java:4128)
       at android.widget.AbsListView.onTouchEvent(AbsListView.java:3886)
       at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:217)
       at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:138)
       at android.view.View.dispatchTouchEvent(View.java:13415)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3054)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2741)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
       at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2554)
       at android.view.View.dispatchPointerEvent(View.java:13674)
       at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5482)
       at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5285)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
       at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4947)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
       at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5004)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4841)
       at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4807)
       at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4815)
       at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4788)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7505)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7474)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7435)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7630)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:336)
       at android.os.Looper.loop(Looper.java:174)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by starboi02** [comment]
Can I work on this?

**Comment by wbrunette** [comment]
@starboi02 I have assigned this issue to you. Please make sure to finish your other issues soon as well.

**Comment by starboi02** [comment]
@wbrunette what steps should I perform to recreate this crash? I am unable to recreate it on my phone.

**Comment by wbrunette** [comment]
I have not re-created the issue myself it was reported to me. My guess is that after screen rotation which destroys everything and recreates it something doesn't get setup correctly.

**Comment by wbrunette** [comment]
@starboi02 I am going to unassign this issue from now. I will see if come back up again in error reporting for testing. It could have been fixed by our many changes for 2.1.8.

**Comment by starboi02** [comment]
Okay @wbrunette. Yeah that could be the case.

**Comment by riturajjain2000** [comment]
@wbrunette sir, this one's fixed as the line which is mentioned in the Log 
`at org.opendatakit.services.MainActivity.onOptionsItemSelected(MainActivity.java:164)` was referring to About Item from the menu, now I have removed that code and made a static function so this is fixed I guess.
Also, I tried recreating it and was unable to
