### ISSUE TITLE
Survey: Crash when UI states do not align

### ISSUE THREAD

**Issue by wbrunette** [opendatakit/tool-suite-X#475]
Crash History:

Fatal Exception: java.lang.IllegalStateException: Getting an createprogress when the dialogs have been cleared for shutdown
       at org.opendatakit.fragment.AlertNProgessMsgFragmentMger.createProgressDialog(AlertNProgessMsgFragmentMger.java:265)
       at org.opendatakit.survey.fragments.InitializationFragment.updateProgressDialog(InitializationFragment.java:192)
       at org.opendatakit.survey.fragments.InitializationFragment.databaseUnavailable(InitializationFragment.java:186)
       at org.opendatakit.application.CommonApplication.possiblyFireDatabaseCallback(CommonApplication.java:459)
       at org.opendatakit.survey.fragments.InitializationFragment.onStart(InitializationFragment.java:95)
       at androidx.fragment.app.Fragment.performStart(Fragment.java:3021)
       at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
       at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3079)
       at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at org.opendatakit.survey.activities.MainMenuActivity.onStart(MainMenuActivity.java:351)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1514)
       at android.app.Activity.performStart(Activity.java:8374)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3869)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:231)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:211)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:183)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:107)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2403)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:204)
       at android.os.Looper.loop(Looper.java:291)
       at android.app.ActivityThread.main(ActivityThread.java:8155)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:601)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1136)

**Comment by Chinex-Boroja** [comment]
Can this issue be assigned to me @wbrunette ?

**Comment by wbrunette** [comment]
@Chinex-Boroja I have assigned the issue to you

**Comment by Chinex-Boroja** [comment]
Hi @wbrunette @Redeem-Grimm-Satoshi 

After cloning the `survey` app and also on upgrade-jdk11 branch, while rebuilding the project, I got an Android resource linking failed: `ERROR: C:\Users\Chinex_Boroja\Desktop\odk-x-apps\survey\survey_app\src\main\res\layout\main_screen.xml:33: AAPT: error: resource color/toolbar_transparent (aka org.opendatakit.survey:color/toolbar_transparent) not found.`

![Resource_Linking_Error](https://github.com/odk-x/tool-suite-X/assets/61055200/3ead4135-684c-409b-88e2-1e2e861ced3a)

I will appreciate any help on this. Thank you

**Comment by wbrunette** [comment]
make sure to set your build variant to "snapshotDebug". Or have androidlibrary checked out in the same directory using the upgrade-jdk11 (make sure to fetch and pull the lastest androidlibrary)

**Comment by wbrunette** [comment]
https://github.com/odk-x/androidlibrary/commits/upgrade-jdk11/

**Comment by Chinex-Boroja** [comment]
Hi @wbrunette I raised a [PR](https://github.com/odk-x/survey/pull/177) for this issue, kindly review. Thank you
